### PR TITLE
Upload only if the db file has changed

### PR DESCRIPTION
**Pull request by inoha-kudo**
This PR ensures that the DB file is uploaded to S3 only when it has changed.
I think it can reduce the possibility of lost data caused by concurrent updates.

### CODE REVIEW

**Comment by mnapoli** [comment]
Beautiful, thanks!

Would it make sense to check the last modification date of the file instead? It would be faster and simpler

**Comment by inoha-naito** [comment]
Thank you for reviewing the Pull Request!

At first, I was also thinking of checking based on the last modified date.
However, the last modified date obtained using the "filemtime" function sometimes returned the same value when executed with 'open' and 'close'.
Please let me know if there is a better way.

**Comment by mnapoli** [comment]
Ah I see, you need to use https://www.php.net/manual/en/function.clearstatcache.php to clear PHP's cache

**Comment by inoha-naito** [comment]
Thanks for giving me your idea!

I tried using "clearstatcache" function but it still sometimes returns the same value.

**Comment by mnapoli** [comment]
Understood, let's work with what you have then 👍

**Pull request merged**
